language: objective-c
osx_image: xcode6.4
before_install:
  - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
  - pod install
  - brew update && brew upgrade xctool
script:
  - rake
